name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run Tests
      working-directory: ./
      run: dotnet test Products.Tests/Products.Tests.csproj --configuration Release --no-build